
package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Omar
 */
public class frmEstacionResultados extends javax.swing.JFrame {

    /**
     * Creates new form frmEstacionResultados
     */
    public frmEstacionResultados() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigoResultado = new javax.swing.JLabel();
        lblNombreResultado = new javax.swing.JLabel();
        lblColorResultado = new javax.swing.JLabel();
        lblMaterialResultado = new javax.swing.JLabel();
        lblCantidadResultado = new javax.swing.JLabel();
        lblCostoResultado = new javax.swing.JLabel();
        lblCostoUnidadResultado = new javax.swing.JLabel();
        lblTiempoResultado = new javax.swing.JLabel();
        lblTiempoUnidadResultado = new javax.swing.JLabel();
        btnVolverEstacionCarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IPCTEC - Trabajo");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Estación de Resultados");

        lblCodigoResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCodigoResultado.setText("Producto: P-01");

        lblNombreResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreResultado.setText("Nombre: Vaso");

        lblColorResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblColorResultado.setText("Color: Rojo");

        lblMaterialResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMaterialResultado.setText("Material: Vidrio");

        lblCantidadResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCantidadResultado.setText("Cantidad: 10");

        lblCostoResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCostoResultado.setText("Costo total: Q20.00");

        lblCostoUnidadResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCostoUnidadResultado.setText("Costo c/u: Q2.00");

        lblTiempoResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTiempoResultado.setText("Tiempo total: 2:50");

        lblTiempoUnidadResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTiempoUnidadResultado.setText("Tiempo c/u: 00:17");

        btnVolverEstacionCarga.setBackground(new java.awt.Color(0, 0, 0));
        btnVolverEstacionCarga.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnVolverEstacionCarga.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverEstacionCarga.setText("Regresar a la estación de carga");
        btnVolverEstacionCarga.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColorResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaterialResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostoUnidadResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCostoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTiempoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTiempoUnidadResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolverEstacionCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodigoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCodigoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCostoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCostoUnidadResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaterialResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempoUnidadResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVolverEstacionCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnVolverEstacionCarga;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblCantidadResultado;
    public javax.swing.JLabel lblCodigoResultado;
    public javax.swing.JLabel lblColorResultado;
    public javax.swing.JLabel lblCostoResultado;
    public javax.swing.JLabel lblCostoUnidadResultado;
    public javax.swing.JLabel lblMaterialResultado;
    public javax.swing.JLabel lblNombreResultado;
    public javax.swing.JLabel lblTiempoResultado;
    public javax.swing.JLabel lblTiempoUnidadResultado;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
    
     //Clase interna que nos servirá para dibujar imagenes en el fondo 
    class FondoPanel extends JPanel {
        private Image imagen;
        
        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondoResultados.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this); //Dibujamos la imagen
            
            setOpaque(false); //Evita que dibuje el fondo por defecto que tiene el panel
            super.paint(g); //Dibuja los componentes por encima de la imagen para que no se pierdan
        }
    }
    
    
}
