
package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Omar
 */
public class frmEstacionTrabajo extends javax.swing.JFrame {

    /**
     * Creates new form frmEstacionTrabajo
     */
    public frmEstacionTrabajo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        lblTitulo = new javax.swing.JLabel();
        lblEnsamblaje = new javax.swing.JLabel();
        lblPintura = new javax.swing.JLabel();
        lblEmpaque = new javax.swing.JLabel();
        pbEnsamblaje = new javax.swing.JProgressBar();
        pbPintura = new javax.swing.JProgressBar();
        pbEmpaque = new javax.swing.JProgressBar();
        lblPorcentajeEnsamblaje = new javax.swing.JLabel();
        lblPorcentajePintura = new javax.swing.JLabel();
        lblPorcentajeEmpaque = new javax.swing.JLabel();
        lblContadorTiempo = new javax.swing.JLabel();
        lblContadorProductos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IPCTEC - Trabajo");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Old English Text MT", 1, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 102));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Estación de Trabajo");

        lblEnsamblaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEnsamblaje.setForeground(new java.awt.Color(0, 0, 0));
        lblEnsamblaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnsamblaje.setText("Ensamblaje");

        lblPintura.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPintura.setForeground(new java.awt.Color(0, 0, 0));
        lblPintura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPintura.setText("Pintura");

        lblEmpaque.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEmpaque.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpaque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpaque.setText("Empaque");

        pbEnsamblaje.setForeground(new java.awt.Color(0, 255, 255));

        pbPintura.setForeground(new java.awt.Color(0, 255, 255));

        pbEmpaque.setForeground(new java.awt.Color(0, 255, 255));

        lblPorcentajeEnsamblaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPorcentajeEnsamblaje.setForeground(new java.awt.Color(0, 0, 0));
        lblPorcentajeEnsamblaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorcentajeEnsamblaje.setText("0%");

        lblPorcentajePintura.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPorcentajePintura.setForeground(new java.awt.Color(0, 0, 0));
        lblPorcentajePintura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorcentajePintura.setText("0%");

        lblPorcentajeEmpaque.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPorcentajeEmpaque.setForeground(new java.awt.Color(0, 0, 0));
        lblPorcentajeEmpaque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorcentajeEmpaque.setText("0%");

        lblContadorTiempo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContadorTiempo.setForeground(new java.awt.Color(51, 0, 0));
        lblContadorTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContadorTiempo.setText("Tiempo: 00:00");

        lblContadorProductos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContadorProductos.setForeground(new java.awt.Color(51, 0, 0));
        lblContadorProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContadorProductos.setText("Productos 1/10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpaque, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPintura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEnsamblaje)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pbPintura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(pbEnsamblaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbEmpaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPorcentajeEnsamblaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentajePintura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentajeEmpaque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblContadorTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblContadorProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContadorProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContadorTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPorcentajeEnsamblaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(pbEnsamblaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblEnsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblPorcentajePintura, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbPintura, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPintura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPorcentajeEmpaque, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(pbEmpaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblEmpaque, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblContadorProductos;
    public javax.swing.JLabel lblContadorTiempo;
    public javax.swing.JLabel lblEmpaque;
    public javax.swing.JLabel lblEnsamblaje;
    public javax.swing.JLabel lblPintura;
    public javax.swing.JLabel lblPorcentajeEmpaque;
    public javax.swing.JLabel lblPorcentajeEnsamblaje;
    public javax.swing.JLabel lblPorcentajePintura;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JProgressBar pbEmpaque;
    public javax.swing.JProgressBar pbEnsamblaje;
    public javax.swing.JProgressBar pbPintura;
    // End of variables declaration//GEN-END:variables

    //Clase interna que nos servirá para dibujar imagenes en el fondo 
    class FondoPanel extends JPanel {
        private Image imagen;
        
        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondoVentanaET.gif")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this); //Dibujamos la imagen
            
            setOpaque(false); //Evita que dibuje el fondo por defecto que tiene el panel
            super.paint(g); //Dibuja los componentes por encima de la imagen para que no se pierdan
        }
    }

}
