
package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Omar
 */
public class frmProducir extends javax.swing.JFrame {

    /**
     * Creates new form frmProducir
     */
    public frmProducir() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        lblCódigo = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        cbbxCodigoProducto = new javax.swing.JComboBox<>();
        txtCatidadProducto = new javax.swing.JTextField();
        btnProducir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Producir");
        setResizable(false);

        lblCódigo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblCódigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCódigo.setText("Código:");

        lblCantidad.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad:");

        cbbxCodigoProducto.setBackground(new java.awt.Color(153, 153, 153));
        cbbxCodigoProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbbxCodigoProducto.setForeground(new java.awt.Color(255, 255, 255));

        txtCatidadProducto.setBackground(new java.awt.Color(153, 153, 153));
        txtCatidadProducto.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtCatidadProducto.setForeground(new java.awt.Color(255, 255, 255));

        btnProducir.setBackground(new java.awt.Color(0, 0, 0));
        btnProducir.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnProducir.setForeground(new java.awt.Color(255, 255, 255));
        btnProducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoVentanProducir.png"))); // NOI18N
        btnProducir.setText("Producir");
        btnProducir.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbxCodigoProducto, 0, 282, Short.MAX_VALUE)
                    .addComponent(txtCatidadProducto))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnProducir, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbxCodigoProducto)
                    .addComponent(lblCódigo, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCatidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(btnProducir)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnProducir;
    public javax.swing.JComboBox<String> cbbxCodigoProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCódigo;
    public javax.swing.JTextField txtCatidadProducto;
    // End of variables declaration//GEN-END:variables
    
    //Clase interna que nos servirá para dibujar imagenes en el fondo 
    class FondoPanel extends JPanel {
        private Image imagen;
        
        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondoVentanaProducir.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this); //Dibujamos la imagen
            
            setOpaque(false); //Evita que dibuje el fondo por defecto que tiene el panel
            super.paint(g); //Dibuja los componentes por encima de la imagen para que no se pierdan
        }
    }
}
